name: Esegui script.py

on:
  push:
    branches:
      - main  # Esegui quando viene fatto un push sul branch principale (main)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codice
      uses: actions/checkout@v2

    - name: Installa Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Scegli la versione di Python che vuoi usare

    - name: Installa requests
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Esegui script
      run: |
        python script.py
